@startuml

actor Enduser
actor "Maintainer" as maintainer

component LAPIS as "LAPIS" {
    [LAPIS-API]
    [SILO]
    portout restInterface as "REST Interface"
}


folder InputData as "Sequence data on disk" {
file nucleotideSequence as "nucleotide_sequence.fasta"
file sortedNucleotideSequence as "sorted_nucleotide_sequence.fasta"
file aminoacidSequence as "aminoacid_sequence.fasta"
file "sorted_aminoacid_sequence.fasta" as sortedAminoacidSequence
file "metadata_and_quality_control.tsv" as metadata
file "nucleotide_insertions.tsv" as nucleotideInsertions
}



file "Configuration File" as config



Enduser <--> restInterface


InputData --> LAPIS


maintainer --> config: provides

config --> LAPIS



@enduml